{
    ALLUSERSPROFILE: 'C:\\ProgramData',
    APPDATA: 'C:\\Users\\as_manchinskiy\\AppData\\Roaming',
    CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_20012_UKVAWFYBFFPMQISH',
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'GORSKAYA-AS',
    ComSpec: 'C:\\Windows\\system32\\cmd.exe',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    EMAIL: 'C:\\Users\\as_manchinskiy\\AppData\\Roaming\\The Bat!',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\as_manchinskiy',
    LOCALAPPDATA: 'C:\\Users\\as_manchinskiy\\AppData\\Local',
    LOGONSERVER: '\\\\S01AD01',
    NUMBER_OF_PROCESSORS: '4',
    OneDrive: 'C:\\Users\\as_manchinskiy\\OneDrive',
    ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
    OS: 'Windows_NT',
    Path: 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\nodejs\\;C:\\Users\\as_manchinskiy\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Git\\cmd;C:\\Users\\as_manchinskiy\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\as_manchinskiy\\AppData\\Roaming\\npm;C:\\Users\\as_manchinskiy\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\liquibase',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: '8c01',
    ProgramData: 'C:\\ProgramData',
    ProgramFiles: 'C:\\Program Files',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PSModulePath: 'C:\\Users\\as_manchinskiy\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    SESSIONNAME: 'Console',
    SystemDrive: 'C:',
    SystemRoot: 'C:\\Windows',
    TEMP: 'C:\\Users\\AS_MAN~1\\AppData\\Local\\Temp',
    TMP: 'C:\\Users\\AS_MAN~1\\AppData\\Local\\Temp',
    USERDNSDOMAIN: 'CS.LOCAL',
    USERDOMAIN: 'CS',
    USERDOMAIN_ROAMINGPROFILE: 'CS',
    USERNAME: 'as_manchinskiy',
    USERPROFILE: 'C:\\Users\\as_manchinskiy',
    VS140COMNTOOLS: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
    windir: 'C:\\Windows',
    ZES_ENABLE_SYSMAN: '1',
    TERM_PROGRAM: 'vscode',
    TERM_PROGRAM_VERSION: '1.70.2',
    LANG: 'ru_RU.UTF-8',
    COLORTERM: 'truecolor',
    GIT_ASKPASS: 'c:\\Users\\as_manchinskiy\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
    VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\as_manchinskiy\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
    VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\as_manchinskiy\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
    VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-c6c106a665-sock'
  }